### ISSUE TITLE
Add support for multiple HPO Terms

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/altamisa#26]
- Semicolon-separated, URL-escape semicolons.
- Should check balance between label, ontology ID, and URL count.
- Result should either be a single entry or a list. Do we need a specific type to indicate such a list? Duck-typing?
- Synchronize with SODAR in terms of parsing.

**Comment by mkuhring** [comment]
Multiple values have been discussed a bit in the ISAforum, but without proper conclusion: https://groups.google.com/forum/?hl=en-GB#!topic/isaforum/HOTScd3EeDY
