### ISSUE TITLE
Add API manual

### ISSUE THREAD

**Issue by mkuhring** [bihealth/altamisa#29]
Mainly use in-line documentation in combination with Sphinx. Add a short description as well as a short tutorial.

**Comment by holtgrewe** [comment]
Basic configuration and structure can be taken from [vcfpy](https://github.com/bihealth/vcfpy/tree/master/docs).

**Comment by holtgrewe** [comment]
Ah, there already was a basic structure. Started with the easy stuff, ready for completing the RST files and then finalizing the docstrings.

- https://altamisa.readthedocs.io/en/latest/

Also already updating the `README.rst`. It looks like we will have to change back to `README.md` the same way as for HLA-MA to get right-aligned images... but that's cosmetics.
