### ISSUE TITLE
Enable assay/study table row order reconstruction

### ISSUE THREAD

**Issue by mkuhring** [bihealth/altamisa#72]
Requestested by @holtgrewe and @mikkonie.

Currently, order information is lost due to the graph transformation. It should be possible to reconstruct an ISA-tab in the same order as imported. Therefore each node needs to keep the info of row origin and the union find algorithm needs to take this information into account. Other applications such as SODAR will benefit from this as well.

This feature partly overlaps with #46.

**Comment by mkuhring** [comment]
I think we should extend that to study and assay order, i.e. in which order they were presented in the investigation file.

**Comment by holtgrewe** [comment]
I don't think that we need to touch the `Investigation` as we are using using tuples for enumerating studies and assays and these already have explicit ordering. It's probably the easiest approach to `enumerate(...)` when importing into SODAR and adding order from there and then just construct the tuple when exporting from SODAR. Also, Python dicts are ordered from 3.6 on (this does not hold for JSONB fields in Postgres).

@mikkonie is that correct?

I think our focus should be on retaining order on the studies and assays on conversion between graph and table. I would not attempt to retain the order of all possible inputs. Retaining order on the sensible inputs is enough plus after the first round trip, round-tripping should not change the file any more.

**Comment by mkuhring** [comment]
Done in a57cceca982a8433e3640e1fddc39abdf798dc5b, thanks to @holtgrewe.
